project_id = "dijldqswhpfzfokcdopm"

[functions.send-dues-reminder]
verify_jwt = false

[functions.create-member-user]
verify_jwt = false

[functions.create-cashier-user]
verify_jwt = false

[functions.delete-cashier-user]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.pirapay-initiate]
verify_jwt = false

[functions.pirapay-webhook]
verify_jwt = false
